#
# This file is part of Docker scripts for the Data Hub System.
# Copyright (C) 2021 INPE.
#
# Docker scripts for the Data Hub System is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: '3'

services:

    dhus:
        build:
            context: ./dhus/
            args:
                BASE_IMAGE: centos:7.8.2003
        image: inpe/dhus:2.0.0-1
        container_name: dhus
        hostname: dhus
        restart: "unless-stopped"
        env_file: .env-dhus
        volumes:
            - "${DHUS_DATA_DIR}:/opt/dhus/2.0.0-1-osf/data"
            - "${DHUS_LOG_DIR}:/opt/dhus/2.0.0-1-osf/log"
            - "${DHUS_CONFIG_DIR}/dhus.xml:/opt/dhus/2.0.0-1-osf/etc/dhus.xml:rw"
            - "${DHUS_CONFIG_DIR}/log4j2.xml:/opt/dhus/2.0.0-1-osf/etc/log4j2.xml"
            - "${DHUS_CONFIG_DIR}/start.sh:/opt/dhus/2.0.0-1-osf/start.sh"
        networks:
            - dhus_net

    nginx:
        image: nginx:1.21.3
        container_name: dhus-nginx
        hostname: dhus-nginx
        restart: unless-stopped
        volumes:
            - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro"
            - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./nginx/ssl:/certs:ro"
            - "${DHUS_NGINX_LOG_DIR}:/var/log/nginx-fs"
        networks:
            - dhus_net
        ports:
            - "443:443"    
        env_file: .env-dhus
        depends_on: 
            - "dhus"

networks:
    dhus_net:
        external: false
        name: dhus_net
